server:
  port: 19091

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service # 라우트 식별자
          uri: lb://user-service  # 'user-service'라는 이름으로 로드 밸런싱된 서비스로 라우팅
          predicates:
            - Path=/api/users/**  # 경로로 들어오는 요청을 이 라우트로 처리
        - id: slack-service
          uri: lb://slack-service
          predicates:
            - Path=/api/slacks/**
        - id: store-service
          uri: lb://store-service
          predicates:
            - Path=/api/stores/**
      discovery:
        locator:
          enabled: true  # 서비스 디스커버리를 통해 동적으로 라우트를 생성하도록 설정


eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/